title: OMU Cloud
description: Ondokuz Mayıs University Cloud Images
logo: /assets/logo/logo.svg
theme: jekyll-theme-minimal
github:
  repository_url: https://github.com/omu/cloud

include:
  - _.html
defaults:
  - scope:
      path: "_.html"
    values:
      permalink: "/_"
